export const NEWS_REQUESTED = 'NEWS_REQUESTED';
export const NEWS_RECEIVED = 'NEWS_RECEIVED';
export const NEWS_FAILED = 'NEWS_FAILED';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const CHANGE_MODAL_TYPE = 'CHANGE_MODAL_TYPE';

export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_RECEIVED = 'AUTH_RECEIVED';
export const AUTH_FAILED = 'AUTH_FAILED';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_RECEIVED = 'LOGIN_RECEIVED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';

export const USER_REQUESTED = 'USER_REQUESTED';
export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_FAILED = 'USER_FAILED';

export const AUTHOR_NEWS_REQUESTED = 'AUTHOR_NEWS_REQUESTED';

export const TOGGLE_EDIT_MODAL = 'TOGGLE_EDIT_MODAL';
export const TOGGLE_NEWS_MODAL = 'TOGGLE_NEWS_MODAL';

export const EDIT_USER_REQUESTED = 'EDIT_USER_REQUESTED';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';
export const EDIT_USER_RECEIVED = 'EDIT_USER_RECEIVED';

export const USER_NEWS_REQUESTED = 'USER_NEWS_REQUESTED';
export const USER_NEWS_RECEIVED = 'USER_NEWS_RECEIVED';
export const USER_NEWS_FAILED = 'USER_NEWS_FAILED';
